create database QL_SACH
use QL_SACH



create table CHUDE
(
	MACD INT PRIMARY KEY NOT NULL,
	TENCHUDE NVARCHAR(40)
)
CREATE TABLE NHAXUATBAN(
	MANXB INT PRIMARY KEY NOT NULL,
	TENNXB NVARCHAR(40),
	DIACHI NVARCHAR(40),
	DIENTHOAI NVARCHAR(11)
)
CREATE TABLE SACH
(
	MASACH INT PRIMARY KEY NOT NULL,
	TENSACH NVARCHAR(40),
	GIABAN DECIMAL(18,2),
	MOTA NVARCHAR(50),
	ANHBIA NVARCHAR(50),
	NGAYCAPNHAT DATE,
	SOLUONGBAN INT,
	MACD INT,
	MANXB INT,
	CONSTRAINT FK_MACD_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
	CONSTRAINT FK_MANXB_SACH FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN(MANXB),

)
CREATE TABLE TACGIA(
	MATG INT PRIMARY KEY NOT NULL,
	TENTG NVARCHAR(30),
	DIACHI_TG NVARCHAR(40),
	TIENST INT ,
	DIENTHOAI_TG NVARCHAR(11)
)

CREATE TABLE VIETSACH
(
	MATG INT,
	MASACH INT,
	CAIGIDO1 NVARCHAR(30),
	CAIGIDO2 NVARCHAR(30),
	CONSTRAINT PK_VIETSACH PRIMARY KEY(MATG,MASACH),
	CONSTRAINT FK_MATG_VIETSACH FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
	CONSTRAINT FK_MASACH_VIETSACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE KHACHHANG 
(
	MAKH INT PRIMARY KEY NOT NULL,
	HOTEN NVARCHAR(30),
	TAIKHOAN NVARCHAR(30),
	MATKHAU NVARCHAR(30),
	EMAIL NVARCHAR(30),
	DIENTHOAI_KH NVARCHAR(11),
	NGAYGIDOKHONGTHAY DATE,
)

CREATE TABLE DONDATHANG
(
	MADONHANG INT PRIMARY KEY NOT NULL,
	DIACHIDONHANG NVARCHAR(30),
	TINHTRANGGIAOHANG NVARCHAR(30),
	NGAYDAT DATE,
	NGAYGIAO DATE,
	MAKH INT,
	CONSTRAINT FK_MAKH_DONDATHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CHITIETDONHANG
(
	MADONHANG INT ,
	MASACH INT,
	SOLUONG_CHITIET INT,
	DONGIA_CHITIET INT,
	CONSTRAINT PK_CHITIET PRIMARY KEY(MADONHANG,MASACH),
	CONSTRAINT FK_MADONHANG_CHITIET FOREIGN KEY (MADONHANG) REFERENCES DONDATHANG(MADONHANG),
	CONSTRAINT DK_MASACH_CHITIET FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

-- Chủ đề
INSERT INTO CHUDE (MACD, TENCHUDE) VALUES
(1, N'Công nghệ'),
(2, N'Tiểu thuyết'),
(3, N'Kinh tế');

-- Nhà xuất bản
INSERT INTO NHAXUATBAN (MANXB, TENNXB, DIACHI, DIENTHOAI) VALUES
(1, N'NXB Kim Đồng', N'Hà Nội', '0123456789'),
(2, N'NXB Trẻ', N'TPHCM', '0987654321');

-- Sách
INSERT INTO SACH (MASACH, TENSACH, GIABAN, MOTA, ANHBIA, NGAYCAPNHAT, SOLUONGBAN, MACD, MANXB) VALUES
(3, N'Khó dỗ dành', 150000, N'Tiểu thuyết của Trúc Dĩ', '‪E:\LuuDuLieuSV\TranNguyenPhuc_2001230693_TLWeb\Tuan_08\Tuan_08_1\BAI2\Content\img\khododanh.jpg', '2023-01-01', 500, 2, 1),
(4, N'Vụng trộm không thể giấu', 150000, N'Tiểu thuyết của Trúc Dĩ', 'csharp.jpg', '2022-01-01', 100, 1, 1),
(5, N'Hái trăng', 150000, N'Tiểu thuyết của Trúc Dĩ', 'csharp.jpg', '2020-01-01', 100, 1, 1);

(1, N'Learning C#', 150000, N'Sách lập trình C# căn bản', 'csharp.jpg', '2024-01-01', 100, 1, 1),
(2, N'Tiểu thuyết ABC', 120000, N'Tiểu thuyết hấp dẫn', 'tieu_thuyet.jpg', '2024-02-15', 50, 2, 2);



-- Tác giả
INSERT INTO TACGIA (MATG, TENTG, DIACHI_TG, TIENST, DIENTHOAI_TG) VALUES
(1, N'Nguyễn Văn A', N'Hà Nội', 1, '0912345678'),
(2, N'Trần Thị B', N'Đà Nẵng', 0, '0987654321');

-- Viết sách
INSERT INTO VIETSACH (MATG, MASACH, CAIGIDO1, CAIGIDO2) VALUES
(1, 1, N'Chương 1', N'Chương 2'),
(2, 2, N'Phần 1', N'Phần 2');

-- Khách hàng
INSERT INTO KHACHHANG (MAKH, HOTEN, TAIKHOAN, MATKHAU, EMAIL, DIENTHOAI_KH, NGAYGIDOKHONGTHAY) VALUES
(1, N'Nguyễn Văn C', N'nguyenvanc', N'123456', 'nvanc@example.com', '0909123456', '2024-05-01');

-- Đơn đặt hàng
INSERT INTO DONDATHANG (MADONHANG, DIACHIDONHANG, TINHTRANGGIAOHANG, NGAYDAT, NGAYGIAO, MAKH) VALUES
(1, N'123 Đường ABC, Hà Nội', N'Chưa giao', '2024-10-01', NULL, 1);

-- Chi tiết đơn hàng
INSERT INTO CHITIETDONHANG (MADONHANG, MASACH, SOLUONG_CHITIET, DONGIA_CHITIET) VALUES
(1, 1, 2, 150000),
(1, 2, 1, 120000);
